const FLC_TPC_GET_USERS_RQ = 'FLC_TPC_GET_USERS_RQ';
const FLC_TPC_GET_USER_RQ = 'FLC_TPC_GET_USER_RQ';
const FLC_TPC_POST_USER_RQ = 'FLC_TPC_POST_USER_RQ';
const FLC_TPC_UPD_USER_RQ = 'FLC_TPC_UPD_USER_RQ';

module.exports = {
  FLC_TPC_GET_USERS_RQ,
  FLC_TPC_GET_USER_RQ,
  FLC_TPC_POST_USER_RQ,
  FLC_TPC_UPD_USER_RQ
};