module.exports = {
  GET_ALL: 'GET_ALL',
  GET_ONE: 'GET_ONE',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',

  FLC_TPC_USER: 'FLC_TPC_USER',
  FLC_TPC_SKILL: 'FLC_TPC_SKILL',
  FLC_TPC_USER_SKILL: 'FLC_TPC_USER_SKILL',
  FLC_TPC_IMAGE: 'FLC_TPC_IMAGE',
};