const FLC_TPC_GET_USERS_RQ = 'FLC_TPC_GET_USERS_RQ';
const FLC_TPC_GET_USERS_RS = 'FLC_TPC_GET_USERS_RS';
const FLC_TPC_GET_USER_BY_ID_RQ = 'FLC_TPC_GET_USER_BY_ID_RQ';
const FLC_TPC_GET_USER_BY_ID_RS = 'FLC_TPC_GET_USER_BY_ID_RS';
const FLC_TPC_POST_USER_RQ = 'FLC_TPC_POST_USER_RQ';
const FLC_TPC_POST_USER_RS = 'FLC_TPC_POST_USER_RS';


module.exports = {
  FLC_TPC_GET_USERS_RQ,
  FLC_TPC_GET_USERS_RS,
  FLC_TPC_GET_USER_BY_ID_RQ,
  FLC_TPC_GET_USER_BY_ID_RS,
  FLC_TPC_POST_USER_RQ,
  FLC_TPC_POST_USER_RS,
};